"""Read-only successor production authority; historical acceptance grants no stages.

This module does not create decisions, receipts, counters, artifacts, or network
requests. Its facts are issued only after the current committed implementation,
external owner source, independent review, and historical H0 evidence agree.
The registered prepare entrypoints retain their scientific and one-shot guards.

Build manifest (external JSON): schema_version, implementation_commit,
source_closure, changed_paths. Independent review (registered JSON):
schema_version, verdict, created_at_utc, reviewer, preregistration_ref,
owner_exception_ref, implementation_binding, registered_checks, changed_paths,
historical_h0_separation. Neither document is generated by this module.
"""

from __future__ import annotations

import ast
import dataclasses
import datetime as dt
import hashlib
import importlib.metadata
import json
import math
import os
import re
import stat
import subprocess
import sys
import sysconfig
import types
import weakref
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any
from zoneinfo import ZoneInfo

from jsonschema import Draft202012Validator, FormatChecker

MATERIALIZATION_MANIFEST_SCHEMA = (
    "p4.2a-successor-production-integration-v1-materialization-manifest-v1"
)
PREFIX = "docs/phase4/reports/P4.2a-successor-production-integration-v1-"
RELEASE_RELATIVE = PREFIX + "production-release-20260907.json"
PREREG_RELATIVE = PREFIX + "preregistration-20260907.json"
EXCEPTION_RELATIVE = PREFIX + "owner-exact-surface-exception-20260907.json"
REVIEW_RELATIVE = PREFIX + "independent-implementation-review-20260907.json"
SCHEMA_RELATIVE = (
    "config/schemas/p4_2a_successor_production_integration_v1_release_authorization.schema.json"
)
MODULE_RELATIVE = "scripts/p4_2a_successor_production_authority.py"
PREPARE_RELATIVE = "scripts/prepare_p4_2a_v2_heldout.py"
BASE_COMMIT = "d7a1f3c001a6243150eb12e1c58efe473c238892"
PREREG_COMMIT = "c59ba4f7e2a8c82a678b040e57145600d1c4564b"
PREREG_SHA = "32f136bfdd4d04474fedf2ee8f0ba3f2c2c4fb160f4ece2712bd1c54810c9bcb"
EXCEPTION_SHA = "3f95b0d1958fb5eb4f04238fa089eb2619dd5ece225c031f875eb56a1bb8959a"
PREPARE_BASE_SHA = "ac2b3eb92ac9fadf823dfc081a1983af57132a77b36bb4f1419297c488eb9394"
PREPARE_TARGET_SHA = "fdcb7fc9063b563ca02fcd630f36e450c1dd04d5b99aa9b2811c11c81eaba1d5"
PATCH_SHA = "aef8e0ce1ad8e4e31a091b7414dd9ef72fb6048b40113c0b1d11a8b568e43ca5"
ALLOWED_STAGES = ("materialize", "infer", "select-blind", "seal-draft", "build-adjudication-ui")
_ALLOWED_CHANGES = {
    PREPARE_RELATIVE: "M",
    MODULE_RELATIVE: "A",
    SCHEMA_RELATIVE: "A",
    "tests/test_p4_2a_successor_production_authority.py": "A",
    "tests/test_p4_2a_successor_preparation_integration.py": "A",
}
_CHECK_IDS = (
    "old_gate_regression",
    "new_gate_fail_closed",
    "historical_h0_integrity",
    "current_source_closure",
    "five_preparation_entries",
    "science_and_retry_invariants",
    "manifest_version_binding",
    "finalize_evaluate_locks",
    "git_lineage_ref_drift",
    "independent_review_requirement",
)
_ORIGIN = Path(__file__).resolve()
_ISSUED: dict[int, tuple[weakref.ReferenceType[Any], bytes]] = {}


class ProductionAuthorityError(RuntimeError):
    """Natural, fail-closed authority validation failure."""


def _require(condition: Any, message: str) -> None:
    if not condition:
        raise ProductionAuthorityError(message)


def _sha(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _canonical(value: Any) -> bytes:
    return (
        json.dumps(
            value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False
        )
        + "\n"
    ).encode("utf-8")


def _read_bytes(path: Path) -> bytes:
    path = Path(path)
    _require(path.is_absolute(), f"absolute path required: {path}")
    # Refuse symlink ancestors as well as a symlink leaf.
    for component in (path, *path.parents):
        _require(not component.is_symlink(), f"symlink evidence/source: {component}")
    try:
        fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
        try:
            before = os.fstat(fd)
            _require(stat.S_ISREG(before.st_mode), f"not a regular file: {path}")
            with os.fdopen(fd, "rb", closefd=False) as stream:
                value = stream.read()
            after = os.fstat(fd)
            _require(
                (
                    before.st_dev,
                    before.st_ino,
                    before.st_size,
                    before.st_mtime_ns,
                    before.st_ctime_ns,
                )
                == (
                    after.st_dev,
                    after.st_ino,
                    after.st_size,
                    after.st_mtime_ns,
                    after.st_ctime_ns,
                ),
                f"file changed during read: {path}",
            )
            return value
        finally:
            os.close(fd)
    except OSError as error:
        raise ProductionAuthorityError(f"cannot read {path}: {error}") from error


def _decode(value: bytes) -> Any:
    def pairs(items: list[tuple[str, Any]]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, item in items:
            _require(key not in result, f"duplicate JSON key: {key}")
            result[key] = item
        return result

    def constant(value: str) -> Any:
        raise ProductionAuthorityError(f"non-finite JSON number: {value}")

    def floating(value: str) -> float:
        result = float(value)
        _require(math.isfinite(result), "non-finite JSON exponent")
        return result

    try:
        return json.loads(
            value.decode("utf-8"),
            object_pairs_hook=pairs,
            parse_constant=constant,
            parse_float=floating,
        )
    except (ValueError, UnicodeError) as error:
        raise ProductionAuthorityError(f"invalid JSON: {error}") from error


def _read_json(path: Path) -> dict[str, Any]:
    result = _decode(_read_bytes(path))
    _require(type(result) is dict, f"expected JSON object: {path}")
    return result


def _relative(value: str) -> str:
    _require(type(value) is str and bool(value), "empty/non-string relative path")
    parsed = PurePosixPath(value)
    _require(
        not parsed.is_absolute()
        and ".." not in parsed.parts
        and parsed.as_posix() == value
        and "\\" not in value,
        f"non-canonical repository path: {value}",
    )
    return value


def _oid(value: str) -> str:
    _require(type(value) is str and re.fullmatch("[0-9a-f]{40}", value), "invalid full commit OID")
    return value


def _git(root: Path, *arguments: str) -> bytes:
    # This is an internal read-only allowlist, not a general command gateway.
    _require(
        bool(arguments)
        and arguments[0]
        in {
            "rev-parse",
            "rev-list",
            "show",
            "cat-file",
            "ls-tree",
            "ls-files",
            "diff",
            "diff-tree",
            "log",
            "for-each-ref",
            "symbolic-ref",
        },
        "unregistered Git operation",
    )
    environment = {
        "PATH": "/usr/bin:/bin:/usr/sbin:/sbin",
        "LANG": "C",
        "LC_ALL": "C",
        "GIT_CONFIG_GLOBAL": "/dev/null",
        "GIT_CONFIG_SYSTEM": "/dev/null",
        "GIT_CONFIG_NOSYSTEM": "1",
        "GIT_OPTIONAL_LOCKS": "0",
        "GIT_NO_REPLACE_OBJECTS": "1",
        "GIT_NO_LAZY_FETCH": "1",
        "GIT_TERMINAL_PROMPT": "0",
        "GIT_ALLOW_PROTOCOL": "",
    }
    result = subprocess.run(
        [
            "/usr/bin/git",
            "-c",
            "core.fsmonitor=false",
            "-c",
            "core.hooksPath=/dev/null",
            "-c",
            "gc.auto=0",
            "-c",
            "core.quotePath=false",
            "-C",
            str(root),
            *arguments,
        ],
        stdin=subprocess.DEVNULL,
        capture_output=True,
        env=environment,
        check=False,
    )
    _require(
        result.returncode == 0,
        f"read-only git {arguments!r}: rc={result.returncode}: "
        + result.stderr.decode("utf-8", errors="replace"),
    )
    return result.stdout


def _repository(root: Path) -> Path:
    root = Path(root)
    _require(root.is_absolute() and root == root.resolve(), "non-canonical root")
    _require(
        (root / ".git").is_dir() and not (root / ".git").is_symlink(),
        "standalone repository required",
    )
    for name in (
        "shallow",
        "info/grafts",
        "objects/info/alternates",
        "objects/info/http-alternates",
    ):
        _require(
            not os.path.lexists(root / ".git" / name),
            f"unsupported Git history indirection: {name}",
        )
    _require(not _git(root, "for-each-ref", "refs/replace").strip(), "replacement refs prohibited")
    _require(
        _git(root, "rev-parse", "--show-toplevel").decode().strip() == str(root),
        "Git root mismatch",
    )
    return root


def _ancestor(root: Path, older: str, newer: str) -> None:
    older, newer = _oid(older), _oid(newer)
    _require(
        _git(root, "cat-file", "-t", older).strip() == b"commit"
        and _git(root, "cat-file", "-t", newer).strip() == b"commit",
        "lineage object is not a commit",
    )
    _require(
        older.encode() in _git(root, "rev-list", newer).splitlines(),
        f"commit {older} not in ancestry of {newer}",
    )


def _refs(root: Path) -> bytes:
    return _git(
        root, "for-each-ref", "--format=%(refname)%00%(objectname)%00%(objecttype)%00%(symref)%00"
    )


def _file_ref(
    root: Path,
    ref: dict[str, Any],
    expected_path: str | None = None,
    expected_sha: str | None = None,
) -> tuple[Path, bytes]:
    _require(type(ref) is dict and {"path", "sha256"} <= ref.keys(), "invalid file reference")
    name = ref["path"]
    _require(type(name) is str, "non-string reference path")
    if expected_path is not None:
        _require(name == expected_path, "reference path drifted")
    path = Path(name) if Path(name).is_absolute() else root / _relative(name)
    value = _read_bytes(path)
    _require(_sha(value) == ref["sha256"], f"reference SHA mismatch: {path}")
    if expected_sha is not None:
        _require(_sha(value) == expected_sha, f"registered SHA mismatch: {path}")
    if "bytes" in ref:
        _require(
            type(ref["bytes"]) is int and len(value) == ref["bytes"],
            f"reference byte count mismatch: {path}",
        )
    return path, value


def _creation(root: Path, path: str, expected_commit: str | None = None) -> str:
    path = _relative(path)
    touches = (
        _git(root, "log", "--all", "--full-history", "--format=%H", "--", path)
        .decode()
        .splitlines()
    )
    _require(len(touches) == 1, f"authority path needs one unique creation: {path}")
    commit = _oid(touches[0])
    if expected_commit is not None:
        _require(commit == _oid(expected_commit), f"creating commit drifted: {path}")
    parents = _git(root, "rev-list", "--parents", "-n", "1", commit).decode().split()
    _require(len(parents) == 2, f"authority creation is not single-parent: {path}")
    changed = (
        _git(root, "diff-tree", "--no-commit-id", "--name-status", "-r", "--no-renames", commit)
        .decode()
        .splitlines()
    )
    _require(changed == ["A\t" + path], f"authority creation is not unique-A: {path}")
    head = _git(root, "rev-parse", "HEAD").decode().strip()
    _ancestor(root, commit, head)
    _require(
        _git(root, "show", f"{commit}:{path}") == _read_bytes(root / path),
        f"authority worktree/creating blob mismatch: {path}",
    )
    _require(
        _git(root, "show", f"HEAD:{path}") == _read_bytes(root / path),
        f"authority HEAD/worktree mismatch: {path}",
    )
    _require(
        _git(root, "show", f":{path}") == _read_bytes(root / path),
        f"authority index/worktree mismatch: {path}",
    )
    return commit


def _authority_ref(
    root: Path,
    ref: dict[str, Any],
    expected_path: str | None = None,
    expected_sha: str | None = None,
) -> tuple[dict[str, Any], str]:
    path, value = _file_ref(root, ref, expected_path, expected_sha)
    _require(path.is_relative_to(root), "authority must be repository-relative")
    commit = _creation(root, path.relative_to(root).as_posix(), ref["creating_commit"])
    parsed = _decode(value)
    _require(type(parsed) is dict, "authority must be an object")
    return parsed, commit


def _tracked_tree(root: Path, commit: str) -> dict[str, tuple[str, str]]:
    result = {}
    for record in _git(root, "ls-tree", "-rz", "--full-tree", _oid(commit)).split(b"\0"):
        if not record:
            continue
        header, raw_path = record.split(b"\t", 1)
        mode, kind, oid = header.decode().split()
        name = _relative(raw_path.decode("utf-8"))
        result[name] = (mode, oid)
        _require(kind != "commit", "Git submodules are not a registered source surface")
    return result


def registered_source_closure(root: Path, implementation_commit: str) -> list[dict[str, Any]]:
    """Inventory every tracked Python/config file, including dynamic imports.

    This deliberately conservative closure avoids an AST-only import graph
    silently omitting function-local imports, wrapper entrypoints or data configs.
    The list comes from Git, never from the supplied manifest.
    """
    root = _repository(root)
    tree = _tracked_tree(root, implementation_commit)
    names = sorted(name for name in tree if name.endswith(".py") or name.startswith("config/"))
    _require(
        {PREPARE_RELATIVE, MODULE_RELATIVE, SCHEMA_RELATIVE} <= set(names),
        "implementation closure lacks required source/schema",
    )
    records = []
    for name in names:
        mode, oid = tree[name]
        _require(mode in {"100644", "100755"}, f"non-regular source: {name}")
        value = _read_bytes(root / name)
        _require(
            _git(root, "cat-file", "blob", oid) == value,
            f"live implementation source drifted: {name}",
        )
        records.append({"path": name, "sha256": _sha(value), "bytes": len(value)})
    return records


def execution_environment() -> dict[str, Any]:
    """Current interpreter/package inventory; no environment installation."""
    executable = Path(sys.executable).resolve()
    packages = sorted(
        (
            {
                "name": re.sub(r"[-_.]+", "-", str(dist.metadata["Name"])).lower(),
                "version": dist.version,
            }
            for dist in importlib.metadata.distributions()
        ),
        key=lambda item: (item["name"], item["version"]),
    )
    _require(
        len({item["name"] for item in packages}) == len(packages),
        "duplicate environment distributions",
    )
    return {
        "interpreter_realpath": str(executable),
        "interpreter_sha256": _sha(_read_bytes(executable)),
        "python_version": sys.version,
        "packages": packages,
        "packages_sha256": _sha(_canonical(packages)),
    }


def _changes(root: Path, commit: str) -> list[dict[str, str]]:
    records = []
    for row in (
        _git(root, "diff", "--name-status", "--no-renames", BASE_COMMIT, _oid(commit))
        .decode()
        .splitlines()
    ):
        status, name = row.split("\t")
        records.append({"status": status, "path": name})
    return sorted(records, key=lambda item: item["path"])


def validate_implementation_binding(
    root: Path,
    implementation_binding: dict[str, Any],
    *,
    reviewed_commit: str | None = None,
) -> dict[str, Any]:
    """Active validator for the actual committed implementation; read-only.

    May inspect an isolated clone. Execution admission additionally validates the
    loaded module origins against that same root; inspection itself grants none.
    """
    _module_integrity()
    root = _repository(root)
    binding = implementation_binding
    _require(
        type(binding) is dict
        and set(binding)
        == {
            "implementation_commit",
            "build_manifest",
            "prepare_exception",
            "source_closure",
            "active_validator",
            "execution_environment",
        },
        "implementation binding fields drifted",
    )
    commit = _oid(binding["implementation_commit"])
    if reviewed_commit is not None:
        _require(commit == reviewed_commit, "reviewed implementation commit mismatch")
    _ancestor(root, BASE_COMMIT, commit)
    _ancestor(root, commit, _git(root, "rev-parse", "HEAD").decode().strip())
    changes = _changes(root, commit)
    _require(
        {x["path"]: x["status"] for x in changes} == _ALLOWED_CHANGES,
        "implementation changed an unregistered surface or lacks a required file",
    )
    for intermediate in _git(root, "rev-list", f"{BASE_COMMIT}..{commit}").decode().splitlines():
        parents = _git(root, "rev-list", "--parents", "-n", "1", intermediate).decode().split()
        _require(len(parents) == 2, "implementation history must remain single-parent")
        for row in (
            _git(
                root,
                "diff-tree",
                "--no-commit-id",
                "--name-status",
                "-r",
                "--no-renames",
                intermediate,
            )
            .decode()
            .splitlines()
        ):
            status, name = row.split("\t")
            _require(
                name in _ALLOWED_CHANGES and status in {"A", "M"},
                "intermediate implementation commit touched a forbidden file",
            )
    _require(
        not _git(root, "diff", "--no-ext-diff", "--name-only", "HEAD").strip(),
        "tracked worktree or index drift",
    )
    _require(
        not _git(root, "diff", "--cached", "--no-ext-diff", "--name-only", "HEAD").strip(),
        "index drift",
    )
    expected_prepare = {
        "path": PREPARE_RELATIVE,
        "base_sha256": PREPARE_BASE_SHA,
        "target_sha256": PREPARE_TARGET_SHA,
        "patch_sha256": PATCH_SHA,
    }
    _require(binding["prepare_exception"] == expected_prepare, "prepare exception drifted")
    _require(
        _sha(_git(root, "show", f"{BASE_COMMIT}:{PREPARE_RELATIVE}")) == PREPARE_BASE_SHA,
        "prepare base bytes drifted",
    )
    _require(
        _sha(_read_bytes(root / PREPARE_RELATIVE)) == PREPARE_TARGET_SHA,
        "prepare target is not the exact reviewed patch",
    )
    closure = registered_source_closure(root, commit)
    _require(binding["source_closure"] == closure, "source closure mismatch/omission")
    closure_map = {item["path"]: item for item in closure}
    _require(
        binding["active_validator"]
        == {
            "path": MODULE_RELATIVE,
            "sha256": closure_map[MODULE_RELATIVE]["sha256"],
            "entrypoint": "validate_implementation_binding",
            "implementation_commit": commit,
        },
        "active validator binding drifted",
    )
    _, raw_manifest = _file_ref(root, binding["build_manifest"])
    manifest = _decode(raw_manifest)
    _require(
        manifest
        == {
            "schema_version": "p4.2a-successor-production-integration-v1-build-manifest",
            "implementation_commit": commit,
            "source_closure": closure,
            "changed_paths": changes,
        },
        "build manifest does not describe actual implementation",
    )
    environment = execution_environment()
    _require(
        binding["execution_environment"] == environment,
        "current interpreter or package set differs from release binding",
    )
    return {
        "implementation_commit": commit,
        "source_closure_sha256": _sha(_canonical(closure)),
        "execution_environment_sha256": _sha(_canonical(environment)),
        "changed_paths": changes,
        "active_validator": binding["active_validator"],
    }


def has_registered_release_candidate(root: Path) -> bool:
    return os.path.lexists(Path(root) / RELEASE_RELATIVE)


def _timestamp(value: str) -> dt.datetime:
    try:
        parsed = dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
        _require(parsed.tzinfo is not None, "timestamp lacks timezone")
        return parsed
    except (ValueError, TypeError, AttributeError) as error:
        raise ProductionAuthorityError("invalid timestamp") from error


def _external_source(root: Path, value: dict[str, Any]) -> dict[str, Any]:
    source = _read_bytes(Path(value["source_path"]))
    _require(
        len(source) == value["source_bytes"] and _sha(source) == value["source_sha256"],
        "owner original source byte/hash mismatch",
    )
    _require(source == value["verbatim_text"].encode("utf-8"), "owner original wording was changed")
    relay_raw = _read_bytes(Path(value["relay_path"]))
    _require(_sha(relay_raw) == value["relay_sha256"], "owner relay SHA mismatch")
    relay = _decode(relay_raw)
    _require(type(relay) is dict, "owner relay is not an object")
    for key in (
        "source_path",
        "source_sha256",
        "source_bytes",
        "verbatim_text",
        "observed_at_utc",
        "delivery_channel",
    ):
        _require(relay.get(key) == value[key], f"owner relay binding mismatch: {key}")
    _require(relay.get("owner_identity") == "ouyang", "owner relay identity mismatch")
    _require(
        _timestamp(value["observed_at_utc"]) <= dt.datetime.now(dt.UTC), "future owner observation"
    )
    return relay


def _registered_checks(
    root: Path, checks: list[dict[str, Any]], policy: dict[str, Any], implementation_commit: str
) -> None:
    # Keep pyexpat helpers out of the frozen v2.1 bootstrap origin census.
    from xml.etree import ElementTree

    _require(
        type(checks) is list
        and len(checks) == len(_CHECK_IDS)
        and {item["check_id"] for item in checks} == set(_CHECK_IDS),
        "missing or duplicate registered checks",
    )
    argv = policy["registered_tests"][0]["proposed_argv"]
    for item in checks:
        _require(
            item["rc"] == 0 and type(item["rc"]) is int and item["status"] == "PASS",
            "registered check did not pass naturally",
        )
        _, command_raw = _file_ref(root, item["command_ref"])
        command = _decode(command_raw)
        _require(
            type(command) is dict
            and command.get("argv") == argv
            and command.get("implementation_commit") == implementation_commit
            and command.get("rc") == 0
            and type(command.get("rc")) is int,
            "registered check argv/commit/result mismatch",
        )
        _require(
            type(command.get("environment")) is dict
            and command["environment"].get("PYTHONDONTWRITEBYTECODE") == "1",
            "registered command environment missing",
        )
        options = command["environment"].get("PYTEST_ADDOPTS", "")
        _require(
            not any(
                token in options
                for token in ("--deselect", "--ignore", "--collect-only", "-k ", "-m ")
            ),
            "registered test command selected a partial suite",
        )
        _require(
            _timestamp(command["ended_at_utc"]) >= _timestamp(command["started_at_utc"]),
            "registered command time order",
        )
        for stream in ("stdout", "stderr"):
            _, raw = _file_ref(root, command[stream])
            _require(_sha(raw) == item[stream + "_sha256"], "registered output SHA mismatch")
        _, report_raw = _file_ref(root, command["junit_xml"])
        _require(
            b"<!DOCTYPE" not in report_raw and b"<!ENTITY" not in report_raw,
            "JUnit entities are forbidden",
        )
        try:
            report = ElementTree.fromstring(report_raw)
        except ElementTree.ParseError as error:
            raise ProductionAuthorityError("invalid registered JUnit report") from error
        cases = list(report.iter("testcase"))
        suites = list(report.iter("testsuite"))
        _require(
            cases
            and suites
            and all(
                not list(case)
                or all(child.tag in {"system-out", "system-err", "properties"} for child in case)
                for case in cases
            ),
            "registered tests include failure/error/skip",
        )
        _require(
            sum(int(suite.attrib["tests"]) for suite in suites) == len(cases)
            and all(
                int(suite.attrib.get(field, "0")) == 0
                for suite in suites
                for field in ("failures", "errors", "skipped")
            ),
            "JUnit counts are inconsistent or not all passed",
        )
        classnames = {case.attrib["classname"] for case in cases}
        required_classes = {
            "tests.test_p4_2a_successor_production_authority",
            "tests.test_p4_2a_successor_preparation_integration",
        }
        _require(classnames == required_classes, "JUnit does not cover both registered files")
        identities = {case.attrib["classname"] + "::" + case.attrib["name"] for case in cases}
        _require(len(identities) == len(cases), "duplicate JUnit test identities")
        coverage = command["check_coverage"]
        _require(
            set(coverage) == set(_CHECK_IDS)
            and all(
                type(nodes) is list and nodes and set(nodes) <= identities
                for nodes in coverage.values()
            ),
            "registered check coverage lacks actual passing test identities",
        )
        evidence = item["evidence_refs"]
        _require(type(evidence) is list and bool(evidence), "missing registered test evidence")
        for ref in evidence:
            _file_ref(root, ref)


def _review(
    root: Path, receipt: dict[str, Any], policy: dict[str, Any], implementation: dict[str, Any]
) -> tuple[dict[str, Any], str]:
    review, commit = _authority_ref(
        root, receipt["independent_implementation_review_ref"], REVIEW_RELATIVE
    )
    required = {
        "schema_version",
        "verdict",
        "created_at_utc",
        "reviewer",
        "preregistration_ref",
        "owner_exception_ref",
        "implementation_binding",
        "registered_checks",
        "changed_paths",
        "historical_h0_separation",
    }
    _require(set(review) == required, "independent review fields drifted")
    _require(
        review["schema_version"]
        == "p4.2a-successor-production-integration-v1-independent-implementation-review",
        "independent review schema mismatch",
    )
    _require(
        review["verdict"] == "PASS_SUCCESSOR_PRODUCTION_INTEGRATION_V1_IMPLEMENTATION_REVIEW",
        "independent implementation review not PASS",
    )
    _require(
        review["reviewer"] == receipt["reviewer"]
        and review["reviewer"]["independent_of_operator"] is True,
        "reviewer declaration mismatch or not independent",
    )
    _require(
        review["preregistration_ref"] == receipt["lineage"]["preregistration"]
        and review["owner_exception_ref"] == receipt["lineage"]["owner_exception"],
        "independent review registration mismatch",
    )
    _require(
        review["implementation_binding"] == receipt["production_implementation_binding"]
        and review["changed_paths"] == implementation["changed_paths"]
        and review["historical_h0_separation"] is True,
        "independent implementation/source binding mismatch",
    )
    _require(
        review["registered_checks"] == receipt["registered_checks"],
        "independent review did not bind registered test outputs",
    )
    _ancestor(root, implementation["implementation_commit"], commit)
    _require(
        _git(root, "rev-parse", commit + "^").decode().strip()
        == implementation["implementation_commit"],
        "review must directly follow implementation",
    )
    _require(
        _timestamp(review["reviewer"]["observed_at_utc"])
        <= _timestamp(review["created_at_utc"])
        <= _timestamp(receipt["created_at_utc"]),
        "independent review time order",
    )
    for ref in review["reviewer"]["evidence_refs"]:
        _file_ref(root, ref)
    _registered_checks(
        root, receipt["registered_checks"], policy, implementation["implementation_commit"]
    )
    return review, commit


@dataclass(frozen=True, slots=True, weakref_slot=True)
class ProductionPreparationAuthorization:
    project_root: Path
    receipt_path: Path
    receipt_sha256: str
    receipt_creating_commit: str
    preregistration_commit: str
    implementation_commit: str
    validated_stage: str | None = None
    reviewed_repository_head: str = ""
    owner_exception_commit: str = ""
    historical_h0_sha256: str = ""
    source_closure_sha256: str = ""
    execution_environment_sha256: str = ""
    evidence_json: bytes = b"{}"
    _seal: object | None = field(default=None, repr=False, compare=False)

    def __reduce__(self) -> Any:
        raise ProductionAuthorityError("production authority cannot be serialized")


def _facts(value: ProductionPreparationAuthorization) -> bytes:
    return _canonical(
        {
            item.name: str(getattr(value, item.name))
            if isinstance(getattr(value, item.name), Path)
            else getattr(value, item.name).decode("utf-8")
            if item.name == "evidence_json"
            else getattr(value, item.name)
            for item in dataclasses.fields(value)
            if item.name != "_seal"
        }
    )


def _issued(value: Any) -> ProductionPreparationAuthorization:
    _require(type(value) is ProductionPreparationAuthorization, "unissued authority type")
    registration = _ISSUED.get(id(value))
    _require(
        registration is not None
        and registration[0]() is value
        and registration[1] == _facts(value),
        "unissued or mutated authority facts",
    )
    return value


def _module_integrity() -> None:
    for name, (original, code) in _FUNCTION_IDENTITIES.items():
        observed = globals().get(name)
        _require(
            observed is original and getattr(observed, "__code__", None) is code,
            f"authority callable was injected: {name}",
        )


def _validate_loaded_callables(module: Any, path: Path, payload: bytes) -> None:
    """Compare repository function code with compilation of its committed bytes.

    Compiling does not execute the module. Decorator wrappers are followed to
    their original callable; closure code remains present in the compiled tree.
    """
    compiled = compile(payload, str(path), "exec", dont_inherit=True, optimize=sys.flags.optimize)
    syntax = ast.parse(payload, filename=str(path))
    declared = {
        node.name
        for node in syntax.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    }
    owned = set(declared)
    for node in syntax.body:
        if (
            isinstance(node, (ast.Assign, ast.AnnAssign))
            and isinstance(node.value, ast.Call)
            and isinstance(node.value.func, ast.Name)
            and node.value.func.id in declared
        ):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            owned.update(
                target.id
                for target in ast.walk(ast.Tuple(elts=targets))
                if isinstance(target, ast.Name)
            )
    expected: set[types.CodeType] = set()

    def visit(code: types.CodeType) -> None:
        expected.add(code)
        for value in code.co_consts:
            if isinstance(value, types.CodeType):
                visit(value)

    visit(compiled)
    for name, function in vars(module).items():
        if name in owned and (callable(function) or name in declared):
            _require(
                getattr(function, "__module__", None) == module.__name__,
                f"loaded repository callable owner differs: {module.__name__}.{name}",
            )
        if not isinstance(function, types.FunctionType) or function.__module__ != module.__name__:
            continue
        seen: set[int] = set()
        while hasattr(function, "__wrapped__"):
            _require(id(function) not in seen, "cyclic callable wrapper")
            seen.add(id(function))
            function = function.__wrapped__
        _require(
            isinstance(function, types.FunctionType)
            and (name not in declared or function.__code__.co_name == name)
            and any(
                function.__code__ == registered
                and function.__code__.co_filename == registered.co_filename
                and function.__code__.co_firstlineno == registered.co_firstlineno
                and function.__code__.co_qualname == registered.co_qualname
                for registered in expected
            ),
            f"loaded repository callable code differs: {module.__name__}.{name}",
        )


def _loaded_origins(root: Path, closure: list[dict[str, Any]]) -> None:
    _require(
        root / MODULE_RELATIVE == _ORIGIN and Path(__file__).resolve() == _ORIGIN,
        "non-canonical authority module",
    )
    _module_integrity()
    source_map = {item["path"]: item for item in closure}
    stdlib = Path(sysconfig.get_path("stdlib")).resolve()
    site_roots = {Path(sysconfig.get_path(key)).resolve() for key in ("purelib", "platlib")}
    for name, module in tuple(sys.modules.items()):
        origin = getattr(module, "__file__", None)
        repository_namespace = (
            name == "scripts"
            or name.startswith("scripts.")
            or name == "alphapilot"
            or name.startswith("alphapilot.")
        )
        if not origin or str(origin).startswith("<"):
            if repository_namespace:
                spec = getattr(module, "__spec__", None)
                locations = getattr(spec, "submodule_search_locations", None)
                expected = root / ("scripts" if name == "scripts" else "src/alphapilot")
                _require(
                    name in {"scripts", "alphapilot"}
                    and locations is not None
                    and {Path(value).resolve() for value in locations} == {expected},
                    f"originless repository module: {name}",
                )
            continue
        path = Path(origin).resolve()
        if path.is_relative_to(root) and ".venv" not in path.relative_to(root).parts:
            relative = path.relative_to(root).as_posix()
            _require(relative in source_map, f"unregistered loaded repository module: {name}")
            payload = _read_bytes(path)
            _require(
                _sha(payload) == source_map[relative]["sha256"],
                f"loaded repository source mismatch: {name}",
            )
            _validate_loaded_callables(module, path, payload)
            if (
                name == "scripts"
                or name.startswith("scripts.")
                or name == "alphapilot"
                or name.startswith("alphapilot.")
            ):
                stem = name.replace(".", "/")
                expected = [root / (stem + ".py"), root / stem / "__init__.py"]
                if name.startswith("alphapilot"):
                    expected = [root / "src" / (stem + ".py"), root / "src" / stem / "__init__.py"]
                _require(path in expected, f"repository module alias/shadow: {name}")
        elif (
            name == "scripts"
            or name.startswith("scripts.")
            or name == "alphapilot"
            or name.startswith("alphapilot.")
        ):
            raise ProductionAuthorityError(f"repository module outside canonical root: {name}")
        else:
            _require(
                path.is_relative_to(stdlib)
                or any(path.is_relative_to(site) for site in site_roots),
                f"loaded module outside registered runtime roots: {name}",
            )


def _validate_policy_scope(receipt: dict[str, Any], policy: dict[str, Any]) -> None:
    _require(
        receipt["authorized_stages"] == list(ALLOWED_STAGES),
        "production release does not grant exactly five preparation stages",
    )
    _require(policy["authorized_stages"] == [], "preregistration is not design-only")
    for key in ("still_gated", "runtime_start_policy", "locks", "failure_policy"):
        _require(receipt[key] == policy[key], f"registered preparation policy drifted: {key}")


def _validate_local_schema_refs(value: Any) -> None:
    if type(value) is dict:
        for key, item in value.items():
            if key in {"$ref", "$dynamicRef", "$recursiveRef"}:
                _require(type(item) is str and item.startswith("#"), "non-local schema reference")
            _validate_local_schema_refs(item)
    elif type(value) is list:
        for item in value:
            _validate_local_schema_refs(item)


def _validate_registered_budget(root: Path, receipt: dict[str, Any]) -> dict[str, Any]:
    """Check the confirmed plan before artifacts/DB access; not a billing meter.

    The original 4048-item frame is a conservative call bound before eligibility
    materialization. Frozen per-call cost is an estimate, never a guaranteed live
    provider charge. Any new price/billing limit needs the independent review.
    """
    relative = "docs/phase4/reports/P4.2a-v2-heldout-preregistration-20260810.json"
    raw = _read_bytes(root / relative)
    _require(
        _sha(raw) == "ccecbf5ca7b48b16e445318b8c94a08927432f92c7e8c12f8ab40f2916578705",
        "frozen heldout plan drifted",
    )
    plan = _decode(raw)
    cost_ref = plan["authorities"]["cost_correction_and_p4_2b_backlog"]
    _, cost_raw = _file_ref(root, cost_ref)
    cost = _decode(cost_raw)
    calls = plan["source_frame"]["expected_raw_candidate_count"]
    per_call = cost["part_1_cost_correction"]["measured_reality"]["cost_per_call"]["qwen3.6-plus"]
    estimated_cost = calls * per_call
    facts = receipt["external_cost_confirmation"]["budget_facts"]
    limits = receipt["execution_limits"]
    _require(
        facts["estimated_model_calls"] == calls and limits["maximum_model_calls"] >= calls,
        "confirmed calls do not cover the registered raw frame",
    )
    _require(
        facts["estimated_cost_cny"] >= estimated_cost
        and limits["maximum_total_cost_cny"] >= facts["estimated_cost_cny"],
        "confirmed budget is below the registered cost estimate",
    )
    bases = facts["basis_refs"]
    _require(
        any(ref["path"] == relative and ref["sha256"] == _sha(raw) for ref in bases)
        and any(
            ref["path"] == cost_ref["path"] and ref["sha256"] == cost_ref["sha256"] for ref in bases
        ),
        "budget lacks the frozen frame/cost basis",
    )
    return {
        "model_calls_upper_bound": calls,
        "historical_cost_estimate_cny": estimated_cost,
        "live_provider_charge_guaranteed": False,
        "billing_meter_performed": False,
    }


def validate_preparation_authorization(
    root: Path,
    *,
    stage: str | None,
) -> ProductionPreparationAuthorization:
    _require(stage is None or stage in ALLOWED_STAGES, f"unregistered stage: {stage!r}")
    root = _repository(Path(root))
    _require(
        root / MODULE_RELATIVE == _ORIGIN, "production authority requires canonical module root"
    )
    _require(
        has_registered_release_candidate(root), "BLOCKED_PENDING_SUCCESSOR_PRODUCTION_OWNER_RELEASE"
    )
    before_refs = _refs(root)
    raw = _read_bytes(root / RELEASE_RELATIVE)
    receipt = _decode(raw)
    schema = _read_json(root / SCHEMA_RELATIVE)
    _validate_local_schema_refs(schema)
    Draft202012Validator.check_schema(schema)
    errors = sorted(
        Draft202012Validator(schema, format_checker=FormatChecker()).iter_errors(receipt),
        key=lambda error: str(error.absolute_path),
    )
    _require(
        not errors,
        "production release schema: "
        + ("; ".join(error.message for error in errors[:8]) if errors else ""),
    )
    _require(raw == _canonical(receipt), "production release must use canonical JSON bytes")
    created = _timestamp(receipt["created_at_utc"])
    shanghai = _timestamp(receipt["created_at_shanghai"])
    _require(
        created.utcoffset() == dt.timedelta(0)
        and shanghai.utcoffset() == dt.timedelta(hours=8)
        and created == shanghai
        and created <= dt.datetime.now(dt.UTC),
        "production release creation timestamps mismatch/future",
    )
    observed = _timestamp(receipt["owner_decision_source"]["observed_at_utc"])
    _require(
        observed <= created
        and receipt["authorization_id"].endswith(
            observed.astimezone(ZoneInfo("Asia/Shanghai")).strftime("%Y%m%d")
        ),
        "authorization ID must use the actual owner issuance day",
    )
    lineage = receipt["lineage"]
    policy, prereg_commit = _authority_ref(
        root, lineage["preregistration"], PREREG_RELATIVE, PREREG_SHA
    )
    _owner, exception_commit = _authority_ref(
        root, lineage["owner_exception"], EXCEPTION_RELATIVE, EXCEPTION_SHA
    )
    _require(
        prereg_commit == PREREG_COMMIT and exception_commit == BASE_COMMIT,
        "registration commit pins drifted",
    )
    _require(
        receipt["historical_anchor_h0"] == policy["historical_anchor_h0"],
        "historical H0 epoch/source distinction drifted",
    )
    _validate_policy_scope(receipt, policy)
    _file_ref(
        root,
        lineage["release_schema"],
        SCHEMA_RELATIVE,
        _sha(_canonical(schema))
        if _read_bytes(root / SCHEMA_RELATIVE) == _canonical(schema)
        else _sha(_read_bytes(root / SCHEMA_RELATIVE)),
    )
    implementation = validate_implementation_binding(
        root, receipt["production_implementation_binding"]
    )
    _loaded_origins(root, receipt["production_implementation_binding"]["source_closure"])
    _review(root, receipt, policy, implementation)
    release_commit = _creation(root, RELEASE_RELATIVE)
    parent = _git(root, "rev-parse", release_commit + "^").decode().strip()
    _require(parent == receipt["reviewed_repository_head"], "release reviewed-head/parent mismatch")
    _require(
        parent == receipt["independent_implementation_review_ref"]["creating_commit"],
        "release must directly follow the independent review",
    )
    _ancestor(root, receipt["independent_implementation_review_ref"]["creating_commit"], parent)
    head = _git(root, "rev-parse", "HEAD").decode().strip()
    _require(head == release_commit, "unreviewed commits after production release")
    for ref in ("refs/heads/main", "refs/remotes/origin/main"):
        _require(
            _git(root, "rev-parse", ref).decode().strip() == head,
            "production release is not registered on main/origin-main",
        )
    _require(
        _git(root, "symbolic-ref", "HEAD").decode().strip() == "refs/heads/main",
        "real preparation requires canonical main checkout",
    )
    owner_relay = _external_source(root, receipt["owner_decision_source"])
    _require(
        owner_relay.get("implementation_commit") == implementation["implementation_commit"]
        and owner_relay.get("independent_review_sha256")
        == receipt["independent_implementation_review_ref"]["sha256"]
        and owner_relay.get("authorization_id") == receipt["authorization_id"]
        and owner_relay.get("verdict") == receipt["verdict"],
        "owner source does not bind this implementation/review/release decision",
    )
    cost = receipt["external_cost_confirmation"]
    cost_relay = _external_source(root, cost["owner_source"])
    _require(
        cost_relay.get("budget_facts") == cost["budget_facts"],
        "owner cost statement does not bind actual budget facts",
    )
    _require(
        _timestamp(cost["owner_source"]["observed_at_utc"]) <= created,
        "cost observation after receipt creation",
    )
    for key in ("maximum_model_calls", "maximum_total_cost_cny", "currency"):
        _require(
            cost["budget_facts"][key] == receipt["execution_limits"][key],
            "owner cost/authorization limit mismatch",
        )
    _require(
        cost["budget_facts"]["estimated_model_calls"] <= cost["budget_facts"]["maximum_model_calls"]
        and cost["budget_facts"]["estimated_cost_cny"]
        <= cost["budget_facts"]["maximum_total_cost_cny"],
        "estimated work exceeds confirmed budget",
    )
    for ref in cost["budget_facts"]["basis_refs"]:
        _file_ref(root, ref)
    registered_budget = _validate_registered_budget(root, receipt)
    _file_ref(root, receipt["supporting_evidence_manifest"])
    historical = _validate_historical_h0(root, policy, receipt)
    _require(_refs(root) == before_refs, "references changed during authority validation")
    evidence = {
        "mode": "successor_production_preparation_only",
        "release_authorization": {
            "path": RELEASE_RELATIVE,
            "sha256": _sha(raw),
            "creating_commit": release_commit,
        },
        "preregistration": lineage["preregistration"],
        "owner_exception": lineage["owner_exception"],
        "implementation_commit": implementation["implementation_commit"],
        "source_closure_sha256": implementation["source_closure_sha256"],
        "execution_environment_sha256": implementation["execution_environment_sha256"],
        "independent_implementation_review": receipt["independent_implementation_review_ref"],
        "historical_h0": historical,
        "authorized_stages": list(ALLOWED_STAGES),
        "still_gated": receipt["still_gated"],
        "locks": receipt["locks"],
        "runtime_start_policy": receipt["runtime_start_policy"],
        "registered_budget": registered_budget,
        "refs_sha256": _sha(before_refs),
    }
    facts = ProductionPreparationAuthorization(
        root,
        root / RELEASE_RELATIVE,
        _sha(raw),
        release_commit,
        prereg_commit,
        implementation["implementation_commit"],
        stage,
        parent,
        exception_commit,
        lineage["h0_evidence_acceptance"]["sha256"],
        implementation["source_closure_sha256"],
        implementation["execution_environment_sha256"],
        _canonical(evidence),
        object(),
    )
    key = id(facts)
    _ISSUED[key] = (weakref.ref(facts, lambda ref: _ISSUED.pop(key, None)), _facts(facts))
    return facts


def validate_registered_production_sources(
    root: Path,
    authorization: ProductionPreparationAuthorization,
    *,
    stage: str,
) -> None:
    _module_integrity()
    facts = _issued(authorization)
    _require(
        stage in ALLOWED_STAGES
        and facts.validated_stage == stage
        and facts.project_root == Path(root).resolve(),
        "authority stage/root mismatch; diagnostic facts cannot admit execution",
    )
    observed = validate_preparation_authorization(Path(root), stage=stage)
    _require(observed == facts, "authority facts changed during revalidation")


def execution_authority_evidence(
    authorization: ProductionPreparationAuthorization,
) -> dict[str, Any]:
    _module_integrity()
    facts = _issued(authorization)
    _require(facts.validated_stage in ALLOWED_STAGES, "diagnostic facts cannot bind real artifacts")
    validate_registered_production_sources(facts.project_root, facts, stage=facts.validated_stage)
    return _decode(facts.evidence_json)


# Historical adapter is defined below; function identities are captured after all
# source definitions. No historical pipeline or consume command is executed.


def _validate_historical_h0(root: Path, policy: dict, receipt: dict) -> dict:
    """Rehash the registered H0 history and its original execution evidence.

    This is a new, read-only historical adapter. It neither calls the former
    consume entry point nor replays a scientific pipeline. The selected epoch 6,
    acceptance-time epoch 9, and current production implementation are distinct.
    Clone file modes are not represented as original publication file modes.
    """
    import json
    import re
    import stat

    def relative(value: str) -> str:
        _require(
            isinstance(value, str)
            and re.fullmatch(r"[A-Za-z0-9._/-]+", value) is not None
            and not value.startswith("/")
            and all(part not in ("", ".", "..") for part in value.split("/")),
            "historical evidence has a noncanonical relative path",
        )
        return value

    def checked_json(raw: bytes):
        def pairs(items):
            result = {}
            for key, value in items:
                _require(key not in result, "duplicate key in historical JSON")
                result[key] = value
            return result

        def constant(value):
            _require(False, "nonfinite value in historical JSON: " + value)

        return json.loads(raw.decode("utf-8"), object_pairs_hook=pairs, parse_constant=constant)

    def tree(directory: Path):
        _require(
            directory.resolve(strict=True) == directory.absolute()
            and stat.S_ISDIR(directory.lstat().st_mode),
            "historical tree root is not a canonical directory",
        )
        before = {}
        identities = {}
        payloads = {}
        for path in [
            directory,
            *sorted(
                directory.rglob("*"),
                key=lambda item: item.relative_to(directory).as_posix().encode("utf-8"),
            ),
        ]:
            name = "." if path == directory else relative(path.relative_to(directory).as_posix())
            metadata = path.lstat()
            before[name] = (
                metadata.st_dev,
                metadata.st_ino,
                metadata.st_mode,
                metadata.st_nlink,
                metadata.st_size,
                metadata.st_mtime_ns,
                metadata.st_ctime_ns,
            )
            if stat.S_ISDIR(metadata.st_mode):
                identities[name] = f"directory:{stat.S_IMODE(metadata.st_mode):04o}"
            else:
                _require(
                    stat.S_ISREG(metadata.st_mode) and metadata.st_nlink == 1,
                    "historical evidence contains a link or special file: " + str(path),
                )
                raw = _read_bytes(path)
                _require(len(raw) == metadata.st_size, "historical evidence size changed")
                payloads[name] = raw
                identities[name] = (
                    f"file:{_sha(raw)}:{stat.S_IMODE(metadata.st_mode):04o}:{metadata.st_nlink}"
                )
        observed = {"."} | {item.relative_to(directory).as_posix() for item in directory.rglob("*")}
        _require(observed == set(before), "historical tree membership changed during read")
        for name, identity in before.items():
            metadata = (directory if name == "." else directory / name).lstat()
            _require(
                identity
                == (
                    metadata.st_dev,
                    metadata.st_ino,
                    metadata.st_mode,
                    metadata.st_nlink,
                    metadata.st_size,
                    metadata.st_mtime_ns,
                    metadata.st_ctime_ns,
                ),
                "historical tree changed during read: " + name,
            )
        return identities, payloads

    def merkle(payloads, leaf_domain, node_domain=b"p4.2a-rehearsal-node-v2.2\0", empty=None):
        if not payloads:
            _require(empty is not None, "historical nonempty Merkle tree is empty")
            return _sha(empty)
        nodes = [
            bytes.fromhex(
                _sha(
                    leaf_domain
                    + relative(name).encode("utf-8")
                    + b"\0"
                    + bytes.fromhex(_sha(payloads[name]))
                )
            )
            for name in sorted(payloads, key=lambda value: value.encode("utf-8"))
        ]
        while len(nodes) > 1:
            next_nodes = []
            for index in range(0, len(nodes), 2):
                left = nodes[index]
                right = nodes[index + 1] if index + 1 < len(nodes) else left
                next_nodes.append(bytes.fromhex(_sha(node_domain + left + right)))
            nodes = next_nodes
        return nodes[0].hex()

    def old_authority(reference):
        """Old registered merge receipts retain their original lineage rules."""
        name = relative(reference["path"])
        digest = reference["sha256"]
        commit = reference["creating_commit"]
        _require(re.fullmatch(r"[0-9a-f]{40}", commit) is not None, "historical commit format")
        _require(re.fullmatch(r"[0-9a-f]{64}", digest) is not None, "historical SHA format")
        raw = _read_bytes(root / name)
        _require(_sha(raw) == digest, "historical registered authority bytes changed: " + name)
        _require(
            _git(root, "show", f"{commit}:{name}") == raw,
            "historical creating-commit blob differs: " + name,
        )
        _require(
            commit in _git(root, "rev-list", "HEAD").decode("ascii").splitlines(),
            "historical authority is not an ancestor",
        )
        return checked_json(raw)

    anchor = policy["historical_anchor_h0"]
    _require(receipt["historical_anchor_h0"] == anchor, "H0 anchor was substituted")
    lineage = receipt["lineage"]
    accepted = anchor["accepted_h0_receipt"]
    _require(lineage["h0_evidence_acceptance"] == accepted, "H0 receipt reference changed")
    h0, h0_commit = _authority_ref(
        root,
        lineage["h0_evidence_acceptance"],
        expected_path=accepted["path"],
        expected_sha=accepted["sha256"],
    )
    _require(h0_commit == accepted["creating_commit"], "H0 creating commit changed")
    completion_ref = policy["H0_completion"]["completion_receipt"]
    _require(lineage["h0_completion"] == completion_ref, "H0 completion reference changed")
    _completion_path, completion_raw = _file_ref(
        root,
        lineage["h0_completion"],
        expected_path=completion_ref["path"],
        expected_sha=completion_ref["sha256"],
    )
    completion = checked_json(completion_raw)
    _require(
        completion["receipt"]["sha256"] == accepted["sha256"]
        and completion["commits"]["E3_receipt"] == h0_commit
        and completion["real_stages_still_locked"] is True,
        "H0 completion does not bind the accepted receipt",
    )

    consume_source = anchor["source"]
    consume_path, consume_raw = _file_ref(
        root,
        consume_source,
        expected_path=consume_source["path"],
        expected_sha=consume_source["sha256"],
    )
    consume = checked_json(consume_raw)
    _require(
        consume["historical_selected_anchor"] == anchor["selected_historical_anchor"]
        and consume["live_execution_anchor"] == anchor["acceptance_time_live_anchor"]
        and consume["release_sha256"] == accepted["sha256"],
        "original H0 consume anchors differ from registration",
    )
    _require(
        consume["mode"] == "PASSIVE_RECOVERED_RELEASE"
        and consume["status"] == "PASS_READ_ONLY_RECOVERED_RELEASE_REVALIDATION",
        "original H0 consume outcome is not the registered natural outcome",
    )
    expected_effects = completion["registered_consume"]["effect_summary"]
    _require(consume["effect_summary"] == expected_effects, "H0 effect summary differs")
    _require(
        expected_effects["before_after_equal"] is True
        and all(
            type(value) is int and value == 0
            for key, value in expected_effects.items()
            if key != "before_after_equal"
        ),
        "original H0 consume disclosed a real side effect",
    )

    # Revalidate the complete, pinned original CONSUME trace, not just its PASS text.
    consume_directory = consume_path.parents[2]
    _require(consume_directory.name == "CONSUME", "unexpected historical consume directory")
    for stage, digest in completion["stage_receipts"].items():
        _require(
            stage in ("PUSH", "CONSUME", "READBACK")
            and _sha(_read_bytes(consume_directory.parent / stage / "complete.json")) == digest,
            "original H0 stage completion changed",
        )
    stage_complete = _read_json(consume_directory / "complete.json")
    _require(
        stage_complete["stage"] == "CONSUME"
        and stage_complete["status"] == "COMPLETE"
        and stage_complete["result"]["registered_consume_invocations"] == 1,
        "historical consume completion identity changed",
    )
    trace_manifest_raw = _read_bytes(consume_directory / "EVIDENCE_MANIFEST.json")
    _require(
        _sha(trace_manifest_raw) == stage_complete["evidence_manifest_sha256"],
        "historical consume trace manifest changed",
    )
    trace_manifest = checked_json(trace_manifest_raw)["inventory"]
    trace_signatures, trace_bytes = tree(consume_directory)
    expected_trace_files = {row["path"]: row for row in trace_manifest["files"]}
    _require(
        len(expected_trace_files) == len(trace_manifest["files"])
        and set(trace_bytes)
        == set(expected_trace_files) | {"complete.json", "EVIDENCE_MANIFEST.json"},
        "original consume trace file inventory differs",
    )
    expected_trace_dirs = {row["path"]: row["mode"] for row in trace_manifest["directories"]}
    actual_trace_dirs = {
        name: int(signature.split(":")[1], 8)
        for name, signature in trace_signatures.items()
        if signature.startswith("directory:")
    }
    _require(actual_trace_dirs == expected_trace_dirs, "original consume trace directories differ")
    for name, row in expected_trace_files.items():
        payload = trace_bytes[relative(name)]
        _require(
            len(payload) == row["bytes"]
            and _sha(payload) == row["sha256"]
            and trace_signatures[name] == f"file:{row['sha256']}:{row['mode']:04o}:1",
            "original consume trace member changed: " + name,
        )
    command_base = "commands/002-registered-consume-readonly-once/"
    command_complete = checked_json(trace_bytes[command_base + "complete.json"])
    command_intent = checked_json(trace_bytes[command_base + "intent.json"])
    # The exact argv is derived from the pinned recovery document below; here bind
    # the captured command and all stdout/result/rc copies without executing it.
    _require(
        command_complete["rc"] == 0
        and command_complete["stdout_sha256"] == _sha(consume_raw)
        and command_complete["stderr_sha256"] == _sha(b"")
        and trace_bytes[command_base + "stdout"] == consume_raw
        and trace_bytes[command_base + "stderr"] == b""
        and trace_bytes["consume.stdout"] == trace_bytes["consume.result.json"] == consume_raw
        and trace_bytes["consume.stderr"] == b""
        and checked_json(trace_bytes["consume-return.json"])["rc"] == 0
        and trace_bytes["before.json"] == trace_bytes["after.json"],
        "original consume command/result/state correspondence differs",
    )
    del trace_bytes

    recovery_policy = policy["accepted_recovery_evidence"]
    bdoc, bcommit = _authority_ref(
        root,
        lineage["b"],
        expected_path=lineage["b"]["path"],
        expected_sha=recovery_policy["owner_binding_sha256"],
    )
    for role, binding in (("q", bdoc["review_request"]), ("r", bdoc["recovery_authorization"])):
        _require(
            lineage[role] == {key: binding[key] for key in ("path", "sha256", "creating_commit")},
            "recovery " + role + " reference differs from the correct B",
        )
    qdoc, qcommit = _authority_ref(
        root,
        lineage["q"],
        expected_path=bdoc["review_request"]["path"],
        expected_sha=bdoc["review_request"]["sha256"],
    )
    rdoc, rcommit = _authority_ref(
        root,
        lineage["r"],
        expected_path=bdoc["recovery_authorization"]["path"],
        expected_sha=recovery_policy["recovery_authorization_sha256"],
    )
    _require(
        bdoc["registered_read_only_recovery_preflight"]["path"] == lineage["q"]["path"]
        and qdoc["proposed_recovery_authorization"]["document"] == rdoc
        and _sha(_canonical(rdoc)) == lineage["r"]["sha256"]
        and bdoc["owner_confirmation"]["confirmation_text"]
        == qdoc["requested_owner_action_time_confirmation"]["requested_exact_confirmation"],
        "recovery Q/R/correct-B cross binding differs",
    )
    _require(
        (qcommit, rcommit, bcommit)
        == (
            "b016d5b4967d3c5004ac5486bd6b80399bb6dda7",
            "e6bb3c03a0be26476a8c263e1d3ca94d240f4387",
            "80f76bba9a078c0eff70d32dc4864a15462762a6",
        ),
        "the accepted recovery Q/R/B creation commits changed",
    )
    _require(
        rdoc["execution_epoch"]["epoch"]
        == anchor["acceptance_time_live_anchor"]["implementation_epoch"]
        == 9
        and rdoc["execution_epoch"]["implementation_commit"]
        == anchor["acceptance_time_live_anchor"]["implementation_commit"]
        and rdoc["execution_epoch"]["control_merkle_root_sha256"]
        == anchor["acceptance_time_live_anchor"]["control_merkle_root_sha256"],
        "recovery execution epoch was confused with the selected historical epoch",
    )
    for role in (
        "independent_implementation_review",
        "landing_report",
        "owner_exact_surface_authorization",
    ):
        old_authority(rdoc["execution_epoch"][role])
    expected_command = list(rdoc["exact_argv"])
    _require(
        expected_command.count("--recover-sealed-bundle") == 1, "registered recovery argv differs"
    )
    expected_command[expected_command.index("--recover-sealed-bundle")] = (
        "--consume-recovered-release"
    )
    _require(
        command_intent["payload_argv"] == expected_command
        and command_intent["environment"] == rdoc["exact_environment"]
        and command_intent["outer_os_sandbox_applied"] is True
        and command_intent["allowed_git_metadata_write"] is False
        and command_intent["network_enabled_for_allowlisted_origin_command"] is False,
        "original consume invocation/isolation differs from registered read-only command",
    )

    bundle_ref = lineage["recovered_bundle"]
    registered_bundle = policy["inherited_authorities"]["lineage_projection"]["bundle"]
    _require(
        bundle_ref["path"] == registered_bundle["path"]
        and bundle_ref["sha256"] == recovery_policy["bundle_sha256"],
        "recovered bundle reference changed",
    )
    bundle_path, bundle_raw = _file_ref(
        root,
        bundle_ref,
        expected_path=registered_bundle["path"],
        expected_sha=recovery_policy["bundle_sha256"],
    )
    bundle = checked_json(bundle_raw)
    bundle_directory = bundle_path.parent
    published_manifest_path = Path(
        "/Users/ouyangduning/Documents/project/interesting/"
        "AlphaPilot-OPERATOR-H0b-evidence-acceptance-20260906.wdzw871f/"
        "bindings/PUBLISHED_TREE_MANIFEST.json"
    )
    published_manifest_raw = _read_bytes(published_manifest_path)
    published_tree_sha = "de1cb094e7532b9669c6dd6a04fabe8cb281a3d9f7675a4a82f33d5e3ade72f6"
    _require(
        _sha(published_manifest_raw) == published_tree_sha, "published historical manifest changed"
    )
    published_manifest = checked_json(published_manifest_raw)
    _require(
        _canonical(published_manifest) == published_manifest_raw,
        "published manifest canonical bytes differ",
    )
    clone_signatures, payloads = tree(bundle_directory)
    _require(
        set(clone_signatures) == set(published_manifest), "published bundle tree membership differs"
    )
    _require(len(payloads) == 160, "published bundle no longer contains exactly 160 files")
    for name, signature in published_manifest.items():
        if signature.startswith("directory:"):
            _require(clone_signatures[name].startswith("directory:"), "bundle directory replaced")
        else:
            _require(
                signature.startswith("file:")
                and name in payloads
                and _sha(payloads[name]) == signature.split(":")[1],
                "published bundle bytes changed: " + name,
            )
    evidence_commit = completion["commits"]["E1_bundle_evidence"]
    repo_prefix = bundle_directory.relative_to(root).as_posix()
    committed_files = (
        _git(root, "ls-tree", "-r", "-z", "--name-only", evidence_commit, "--", repo_prefix)
        .decode("utf-8")
        .split("\0")
    )
    _require(
        {name for name in committed_files if name}
        == {repo_prefix + "/" + name for name in payloads},
        "H0 E1 Git bundle inventory differs",
    )
    for name, raw in payloads.items():
        _require(
            _git(root, "show", f"{evidence_commit}:{repo_prefix}/{name}") == raw,
            "H0 E1 Git bundle blob differs: " + name,
        )

    # Recompute every registered archive inventory and its Merkle roots.
    archives = bundle["archive"]
    history_archive = archives["attempt_history"]
    history_prefix = relative(history_archive["archive_root"]) + "/"
    history_payloads = {
        name: raw for name, raw in payloads.items() if name.startswith(history_prefix)
    }
    history_files = {row["path"]: row["sha256"] for row in history_archive["files"]}
    _require(
        len(history_files) == len(history_archive["files"]) == history_archive["file_count"] == 50
        and set(history_files) == set(history_payloads)
        and all(_sha(history_payloads[name]) == digest for name, digest in history_files.items()),
        "complete attempt-history archive inventory differs",
    )
    generic_leaf = b"p4.2a-rehearsal-leaf-v2.2\0"
    _require(
        merkle(history_payloads, generic_leaf) == history_archive["history_merkle_root_sha256"],
        "attempt-history archive Merkle root differs",
    )
    control = archives["control_surface"]
    control_manifest_ref = control["manifest"]
    control_manifest_path = relative(control_manifest_ref["bundle_relative_path"])
    control_manifest_raw = payloads[control_manifest_path]
    control_manifest = checked_json(control_manifest_raw)
    _require(
        _sha(control_manifest_raw) == control_manifest_ref["sha256"]
        and len(control_manifest_raw) == control_manifest_ref["bytes"]
        and control_manifest["files"] == control["files"]
        and len(control["files"]) == control["file_count"] == 80,
        "historical control manifest differs",
    )
    control_payloads = {control_manifest_path: control_manifest_raw}
    selected = anchor["selected_historical_anchor"]
    for row in control["files"]:
        name = relative(row["bundle_relative_path"])
        _require(name not in control_payloads, "duplicate historical control member")
        raw = payloads[name]
        _require(_sha(raw) == row["sha256"] and len(raw) == row["bytes"], "control member changed")
        control_payloads[name] = raw
        if row["repository_path"] is not None:
            repository_name = relative(row["repository_path"])
            _require(
                _git(root, "show", f"{selected['implementation_commit']}:{repository_name}") == raw,
                "selected-epoch historical control Git blob differs: " + repository_name,
            )
    _require(
        set(control_payloads)
        == {
            name
            for name in payloads
            if name == control_manifest_path or name.startswith(control["archive_root"] + "/")
        }
        and merkle(control_payloads, generic_leaf) == selected["control_merkle_root_sha256"],
        "historical control closure or Merkle root differs",
    )
    run_roots = {}
    run_members = {}
    _require(len(archives["runs"]) == 2, "historical deterministic run count changed")
    for run in archives["runs"]:
        label = run["run_label"]
        _require(label in ("run-a", "run-b") and label not in run_roots, "run label changed")
        members = {}
        for row in run["artifacts"]:
            name = relative(row["source_relative_path"])
            _require(name not in members, "duplicate run artifact")
            raw = payloads[relative(run["archive_root"]) + "/" + name]
            _require(
                _sha(raw) == row["sha256"] and len(raw) == row["bytes"], "run artifact changed"
            )
            members[name] = raw
            selected_copy = (
                history_prefix + "attempts/000002/evidence/runs/" + label + "/root/" + name
            )
            _require(payloads[selected_copy] == raw, "selected attempt/run archive bytes differ")
        _require(
            len(members) == run["artifact_count"] == 14
            and {
                name[len(run["archive_root"]) + 1 :]
                for name in payloads
                if name.startswith(run["archive_root"] + "/")
            }
            == set(members),
            "run artifact closure differs",
        )
        run_roots[label] = merkle(members, generic_leaf)
        _require(run_roots[label] == run["artifact_merkle_root_sha256"], "run Merkle root differs")
        run_members[label] = members
    _require(
        run_members["run-a"] == run_members["run-b"], "14-of-14 deterministic equality differs"
    )

    history = bundle["attempt_history"]
    records = history["records"]
    _require(
        len(records)
        == history["started_count"]
        == h0["attempt_history_acceptance"]["attempt_count"]
        == 2
        and [row["ordinal"] for row in records] == [1, 2],
        "historical attempt counts, order, or continuity differs",
    )
    previous = _sha(b"p4.2a-rehearsal-v2.2-history-empty-v1\0")
    recomputed_records = []
    for record in records:
        ordinal = record["ordinal"]
        ordinal_bytes = ordinal.to_bytes(8, "big")
        _require(
            record["previous_history_root_sha256"] == previous,
            "historical chain predecessor differs",
        )
        token = _sha(
            b"p4.2a-rehearsal-v2.2-attempt-v1\0"
            + bytes.fromhex(history["series_token_sha256"])
            + ordinal_bytes
            + bytes.fromhex(record["implementation_commit"])
            + bytes.fromhex(previous)
        )
        _require(token == record["attempt_token_sha256"], "historical attempt token differs")
        artifact_payloads = {}
        evidence_prefix = history_prefix + f"attempts/{ordinal:06d}/evidence/"
        for item in record["artifact_inventory"]:
            name = relative(item["relative_path"])
            archived = relative(item["archive_relative_path"])
            _require(
                archived == evidence_prefix + name and name not in artifact_payloads,
                "attempt artifact path differs",
            )
            raw = payloads[archived]
            _require(
                _sha(raw) == item["sha256"] and len(raw) == item["bytes"],
                "attempt artifact changed",
            )
            artifact_payloads[name] = raw
        _require(
            {name[len(evidence_prefix) :] for name in payloads if name.startswith(evidence_prefix)}
            == set(artifact_payloads),
            "attempt evidence closure omits a member",
        )
        evidence_root = merkle(
            artifact_payloads,
            b"p4.2a-rehearsal-v2.2-evidence-leaf-v1\0",
            b"p4.2a-rehearsal-v2.2-evidence-node-v1\0",
            b"p4.2a-rehearsal-v2.2-evidence-empty-v1\0",
        )
        _require(
            evidence_root == record["evidence_tree_root_sha256"], "attempt evidence Merkle differs"
        )
        documents = {}
        document_hashes = {}
        for role in ("started", "candidate", "terminal"):
            item = record[role]
            if item is None:
                _require(
                    role == "candidate" and ordinal == 1, "historical terminal/started disappeared"
                )
                document_hashes[role] = bytes(32)
                continue
            archived = relative(item["archive_relative_path"])
            _require(
                archived == history_prefix + item["live_relative_path"],
                "attempt document path differs",
            )
            raw = payloads[archived]
            _require(
                _sha(raw) == item["sha256"] and len(raw) == item["bytes"],
                "attempt document changed",
            )
            documents[role] = checked_json(raw)
            document_hashes[role] = bytes.fromhex(_sha(raw))
        started = documents["started"]
        terminal = documents["terminal"]
        _require(
            all(
                started[key] == record[key]
                for key in (
                    "ordinal",
                    "implementation_commit",
                    "implementation_epoch",
                    "attempt_token_sha256",
                    "previous_history_root_sha256",
                )
            )
            and started["series_token_sha256"] == history["series_token_sha256"]
            and terminal["outcome"] == record["outcome"]
            and terminal["reached_stage"] == record["reached_stage"]
            and record["automatic_retry_count"] == 0,
            "attempt started/terminal semantics differ",
        )
        command_hash = _sha(
            b"p4.2a-v2.2-argv-v1\0"
            + b"\0".join(value.encode("utf-8") for value in started["command"])
        )
        environment_bytes = bytearray(b"p4.2a-v2.2-env-v1\0")
        for key in sorted(started["environment"], key=lambda value: value.encode("utf-8")):
            environment_bytes.extend(key.encode("utf-8") + b"\0")
            environment_bytes.extend(started["environment"][key].encode("utf-8") + b"\0")
        _require(
            command_hash == started["command_sha256"] == record["command_sha256"]
            and _sha(bytes(environment_bytes))
            == started["environment_sha256"]
            == record["environment_sha256"],
            "historical exact command or environment hash differs",
        )
        action = record["owner_action_time_authorization"]
        action_doc = old_authority(action["authority"])
        action_raw = payloads[relative(action["archive_relative_path"])]
        _require(
            _sha(action_raw) == action["archive_sha256"] == action["authority"]["sha256"]
            and checked_json(action_raw) == action_doc
            and len(action_raw) == action["bytes"],
            "historical action authorization archive differs",
        )
        record_root = _sha(
            b"p4.2a-rehearsal-v2.2-attempt-record-v1\0"
            + ordinal_bytes
            + bytes.fromhex(token)
            + document_hashes["started"]
            + document_hashes["candidate"]
            + document_hashes["terminal"]
            + bytes.fromhex(evidence_root)
        )
        _require(
            record_root == record["record_root_sha256"], "historical attempt record Merkle differs"
        )
        previous = _sha(
            b"p4.2a-rehearsal-v2.2-history-step-v1\0"
            + bytes.fromhex(previous)
            + bytes.fromhex(record_root)
        )
        recomputed_records.append(
            {
                "implementation_epoch": record["implementation_epoch"],
                "ordinal": ordinal,
                "outcome": record["outcome"],
                "record_root_sha256": record_root,
            }
        )
        if ordinal == 2:
            candidate = documents["candidate"]
            candidate_root = _sha(
                b"p4.2a-rehearsal-v2.2-candidate-content-v1\0"
                + bytes.fromhex(record["previous_history_root_sha256"])
                + bytes.fromhex(run_roots["run-a"])
                + bytes.fromhex(run_roots["run-b"])
                + bytes.fromhex(selected["control_merkle_root_sha256"])
                + bytes.fromhex(evidence_root)
            )
            _require(
                candidate_root
                == candidate["candidate_content_root_sha256"]
                == rdoc["sealed_series"]["selected_candidate_content_root_sha256"]
                and candidate["implementation_epoch"] == selected["implementation_epoch"] == 6
                and candidate["implementation_commit"] == selected["implementation_commit"]
                and candidate["run_a_root_sha256"] == run_roots["run-a"]
                and candidate["run_b_root_sha256"] == run_roots["run-b"],
                "selected historical candidate binding differs",
            )
    _require(
        [row["outcome"] for row in records] == ["FAILED", "CANDIDATE_VALIDATED_AND_SELECTED"]
        and history["failed_count"] == 1
        and history["incomplete_count"] == 0
        and history["validated_candidate_count"] == 1
        and history["selected_attempt_ordinal"] == 2
        and history["series_closed"] is True
        and previous == history["history_root_sha256"] == selected["history_root_sha256"]
        and recomputed_records == h0["owner_authorization"]["acknowledged_outcomes"],
        "history count, selected outcome, owner acknowledgement, or final root differs",
    )
    bundle_root = _sha(
        b"p4.2a-rehearsal-bundle-v2.2\0"
        + bytes.fromhex(previous)
        + bytes.fromhex(run_roots["run-a"])
        + bytes.fromhex(run_roots["run-b"])
        + bytes.fromhex(selected["control_merkle_root_sha256"])
    )
    _require(
        bundle_root == bundle["merkle"]["bundle_root_sha256"] == h0["lineage"]["bundle_root_sha256"]
        and bundle["merkle"]["attempt_history_root_sha256"] == previous,
        "final historical bundle Merkle root differs",
    )
    _require(
        [epoch["epoch"] for epoch in bundle["implementation_epochs"]] == [5, 6],
        "historical epochs changed",
    )
    for epoch, accepted_epoch in zip(
        bundle["implementation_epochs"], h0["implementation_epochs"], strict=True
    ):
        for key in (
            "epoch",
            "implementation_commit",
            "control_merkle_root_sha256",
            "first_attempt_ordinal",
            "last_attempt_ordinal",
        ):
            _require(epoch[key] == accepted_epoch[key], "H0 epoch acknowledgement differs")
        _require(
            epoch["owner_exact_surface_authorization"]
            == accepted_epoch["owner_surface_authorization"]
            and epoch["independent_implementation_review"]
            == accepted_epoch["independent_implementation_review"],
            "historical epoch authorities differ",
        )
        old_authority(epoch["owner_exact_surface_authorization"])
        old_authority(epoch["independent_implementation_review"])

    # Physical ledger/mirror are still original evidence. Their bytes and modes
    # are checked as physical state, separately from the clone's copied bundle.
    ledger_payloads = {
        name[len(history_prefix) :]: raw
        for name, raw in history_payloads.items()
        if not name.endswith("/action-time-authorization.json")
    }
    _require(len(ledger_payloads) == 48, "sealed ledger inventory count differs")
    live_root = merkle(ledger_payloads, b"p4.2a-rehearsal-v2.2-ledger-leaf-v1\0")
    _require(
        live_root == history["live_ledger_root_sha256"] == selected["live_ledger_root_sha256"],
        "sealed ledger Merkle root differs",
    )
    sealed = rdoc["sealed_series"]
    ledger_signatures, original_ledger = tree(Path(sealed["ledger_root"]))
    mirror_signatures, original_mirror = tree(Path(sealed["sealed_mirror"]["latest_snapshot_path"]))
    _require(
        original_ledger == original_mirror == ledger_payloads,
        "sealed physical ledger/mirror bytes differ",
    )
    _require(
        ledger_signatures == mirror_signatures, "sealed physical ledger/mirror metadata differ"
    )
    physical_ledger_sha = _sha(_canonical(ledger_signatures))
    del original_ledger, original_mirror
    mirror_policy = sealed["sealed_mirror"]
    mirror_receipt_a = _read_bytes(Path(mirror_policy["primary_receipt_path"]))
    mirror_receipt_b = _read_bytes(Path(mirror_policy["secondary_receipt_path"]))
    _require(
        mirror_receipt_a == mirror_receipt_b
        and _sha(mirror_receipt_a) == mirror_policy["receipt_sha256"]
        and len(mirror_receipt_a) == mirror_policy["receipt_bytes"],
        "sealed ledger paired receipts differ",
    )

    storage = rdoc["destination"]["recovery_storage"]
    receipt_name = (
        "recovery-"
        + lineage["r"]["sha256"]
        + "-"
        + published_tree_sha
        + ".bundle-mirror-verification.json"
    )
    paired_bytes = []
    for role, container_key in (
        ("primary", "primary_recovery_container"),
        ("secondary", "secondary_recovery_container"),
    ):
        expected_path = str(Path(storage[container_key]) / receipt_name)
        _path, raw = _file_ref(
            root,
            lineage["paired_recovery_receipts"][role],
            expected_path=expected_path,
            expected_sha=recovery_policy["paired_receipt_sha256"],
        )
        paired_bytes.append(raw)
    _require(
        paired_bytes[0] == paired_bytes[1],
        "recovered bundle paired receipts are not byte-identical",
    )
    recovered_receipt = checked_json(paired_bytes[0])
    _require(
        recovered_receipt["published_bundle_sha256"] == _sha(bundle_raw)
        and recovered_receipt["published_tree_sha256"] == published_tree_sha
        and recovered_receipt["secondary_snapshot_tree_sha256"] == published_tree_sha
        and recovered_receipt["selected_implementation_epoch"] == 6
        and recovered_receipt["execution_epoch"] == 9
        and recovered_receipt["execution_head"] == bcommit
        and recovered_receipt["selected_implementation_commit"] == selected["implementation_commit"]
        and recovered_receipt["execution_implementation_commit"]
        == anchor["acceptance_time_live_anchor"]["implementation_commit"]
        and recovered_receipt["pipeline_starts"] == recovered_receipt["automatic_retry_count"] == 0,
        "recovered bundle receipt anchors differ",
    )
    expected_snapshot = Path(storage["secondary_recovery_container"]) / (
        "RECOVERED-BUNDLE-" + lineage["r"]["sha256"] + "-" + published_tree_sha
    )
    _require(
        recovered_receipt["secondary_snapshot"] == str(expected_snapshot),
        "secondary snapshot path differs",
    )
    snapshot_signatures, snapshot_payloads = tree(expected_snapshot)
    _require(
        snapshot_signatures == published_manifest and snapshot_payloads == payloads,
        "original published secondary snapshot differs from the historical manifest/clone bytes",
    )
    del snapshot_payloads
    claim_root = Path(storage["primary_recovery_container"]) / ("CLAIM-" + lineage["r"]["sha256"])
    claim_start = _read_json(claim_root / "started.json")
    terminal_raw = _read_bytes(claim_root / "terminal.json")
    terminal = checked_json(terminal_raw)
    _require(
        _sha(terminal_raw) == consume["claim_terminal_sha256"],
        "accepted recovery terminal bytes changed",
    )
    _require(
        claim_start["authorized_bundle_recovery_starts"] == 1
        and claim_start["authorized_pipeline_starts"] == claim_start["automatic_retry_count"] == 0
        and claim_start["execution_head"] == bcommit
        and claim_start["execution_epoch"] == 9
        and terminal["outcome"] == "BUNDLE_RECOVERY_PUBLISHED_MIRRORED_AND_RECEIPTED"
        and terminal["reached_stage"] == "paired_receipts_verified"
        and terminal["error"] is None
        and terminal["pipeline_starts"] == terminal["automatic_retry_count"] == 0
        and terminal["published_tree_sha256"] == published_tree_sha
        and terminal["published_bundle_sha256"] == _sha(bundle_raw)
        and terminal["sealed_ledger_before_sha256"]
        == terminal["sealed_ledger_after_sha256"]
        == terminal["sealed_mirror_before_sha256"]
        == terminal["sealed_mirror_after_sha256"]
        == physical_ledger_sha,
        "original recovery start/terminal or physical ledger binding differs",
    )
    for doc in (claim_start, terminal):
        _require(
            {key: doc["authorization"][key] for key in ("path", "sha256", "creating_commit")}
            == lineage["r"]
            and {
                key: doc["owner_confirmation_binding"][key]
                for key in ("path", "sha256", "creating_commit")
            }
            == lineage["b"],
            "recovery claim lost its R/B creating-commit binding",
        )
    _require(
        not Path(claim_start["destination_stage"]).exists()
        and not Path(claim_start["destination_stage"]).is_symlink()
        and not Path(claim_start["secondary_snapshot_stage"]).exists()
        and not Path(claim_start["secondary_snapshot_stage"]).is_symlink(),
        "a completed recovery staging path reappeared",
    )
    _require(
        consume["bundle_sha256"] == _sha(bundle_raw)
        and consume["paired_receipt_sha256"] == _sha(paired_bytes[0])
        and consume["owner_binding_sha256"] == lineage["b"]["sha256"]
        and consume["recovery_authorization_sha256"] == lineage["r"]["sha256"]
        and consume["real_lineage_census_sha256"] == recovery_policy["real_lineage_census_sha256"],
        "original H0 consume no longer binds the same recovery evidence",
    )
    return {
        "status": "PASS_HISTORICAL_H0_BYTES_GIT_MERKLE_AND_ORIGINAL_TRACE",
        "h0_receipt_sha256": accepted["sha256"],
        "h0_receipt_creating_commit": h0_commit,
        "h0_completion_sha256": _sha(completion_raw),
        "historical_consume_stdout_sha256": _sha(consume_raw),
        "historical_consume_trace_manifest_sha256": _sha(trace_manifest_raw),
        "historical_consume_trace_files_verified": len(expected_trace_files),
        "published_bundle_sha256": _sha(bundle_raw),
        "published_tree_manifest_sha256": published_tree_sha,
        "bundle_files_verified_against_git_and_secondary_snapshot": len(payloads),
        "control_members_verified": len(control["files"]),
        "history_archive_files_verified": len(history_payloads),
        "sealed_ledger_files_verified": len(ledger_payloads),
        "attempt_count": len(records),
        "failed_count": 1,
        "incomplete_count": 0,
        "selected_attempt_ordinal": 2,
        "history_root_sha256": previous,
        "live_ledger_root_sha256": live_root,
        "bundle_merkle_root_sha256": bundle_root,
        "paired_recovery_receipt_sha256": _sha(paired_bytes[0]),
        "recovery_terminal_sha256": _sha(terminal_raw),
        "historical_selected_anchor": selected,
        "acceptance_time_live_anchor": anchor["acceptance_time_live_anchor"],
        "current_production_source_validation_performed": False,
        "scientific_pipeline_replayed": False,
        "old_consume_entry_point_invoked": False,
        "clone_permissions_claimed_as_original": False,
    }


_FUNCTION_IDENTITIES = {
    name: (value, value.__code__)
    for name, value in tuple(globals().items())
    if isinstance(value, types.FunctionType) and value.__module__ == __name__
}
